version: '3.1'

services:
  db:
    image: postgres:16.1
    environment:
      - POSTGRES_USER: ${POSTGRES_USER}
      - POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      - POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - - ${POSTGRES_PORT}:5432
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
