version: '3.1'

services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: ${DJANGO_DATABASE_USER}
      POSTGRES_PASSWORD: ${DJANGO_DATABASE_PASSWORD}
      POSTGRES_DB: ${DJANGO_DATABASE_DB_NAME}
    ports:
      - ${DJANGO_DATABASE_PORT}:5432
    volumes:
      - ./.postgres-data_old:/var/lib/postgresql/data
