# Generated by Django 5.1.1 on 2024-09-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number_plates_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
