# Generated by Django 5.1.1 on 2024-09-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_limit', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
